name: CI Main

on:
  push:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarCloud analysis (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        - name: SonarCloud Scan
          uses: SonarSource/sonarqube-scan-action@v8.1.0
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >-
              -Dsonar.host.url=${{ secrets.SONAR_URL }}
              -Dsonar.organization=${{ secrets.SONAR_ORG }}
              -Dsonar.projectKey=lanzar-dev_devsecops-demo
              -Dsonar.projectName=lanzar-dev_devsecops-demo
              -Dsonar.sources=.
              -Dsonar.qualitygate.wait=true
              -Dsonar.qualitygate.timeout=300
